In [1]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
sys.path.append(module_path)

import src.remo3d as rm
import numpy as np

In [2]:
np.set_printoptions(suppress = True)

In [3]:
# Specify input data
# tools = ["B5.7A0.4M", "M5.7N0.4A", "M2.0A0.5B", "A2.0M0.5N"] # logging tools
tools = ["B5.7A0.4M", "B4.48A1.62M", "M1.0A0.1B", "A2.0M0.5N", "N0.5M2.0A", "M4.0A0.5B"] # logging tools
formation_model_file = "./Input/Formation.txt" # path to file with formation parameters
borehole_model_file = "./Input/Borehole.txt" # path to file with borehole parameters
measurement_depths = np.arange(0, 25.1, 0.25) # measurement points

In [4]:
# Set model parameters
model_parameters = rm.SetModelParameters(formation_model_file, borehole_model_file)
# model_parameters

In [5]:
# Set tools parameters
tools_parameters = rm.SetToolsParameters(tools)

for tool in list(tools_parameters.keys()):
    print(tool)
    print(tools_parameters[tool])
    print()

B5.7A0.4M
[[-5.9        -0.2         0.2         5.37928847]
 [-1.          1.          0.         -3.05      ]]

B4.48A1.62M
[[-5.29       -0.81        0.81       27.71894518]
 [-1.          1.          0.         -3.05      ]]

M1.0A0.1B
[[ -1.05        -0.05         0.05       138.23007676]
 [  0.           1.          -1.           0.        ]]

A2.0M0.5N
[[ -2.25        -0.25         0.25       125.66370614]
 [  1.           0.           0.          -2.25      ]]

N0.5M2.0A
[[ -0.25         0.25         2.25       125.66370614]
 [  0.           0.           1.           2.25      ]]

M4.0A0.5B
[[ -4.25        -0.25         0.25       452.38934212]
 [  0.           1.          -1.           0.        ]]



In [ ]:
measurement_depths_mask = np.all(np.vstack([measurement_depths>=2, measurement_depths<=23]).T, axis=1)
logs = rm.ComputeSyntheticLogs_v2(tools_parameters, model_parameters, measurement_depths, measurement_depths_mask=measurement_depths_mask, force_single_electrode_configuration=True)

/mnt/c/users/MW/GitHub/ReMo3D/src/remo3d.py:1987: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if measurement_depths_mask=="None":
