In [1]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
sys.path.append(module_path)

import src.remo3d as rm
import numpy as np

In [2]:
np.set_printoptions(suppress = True)

In [3]:
# Specify input data
tools = ["B5.7A0.4M", "M5.7N0.4A", "M2.0A0.5B", "A2.0M0.5N"] # logging tools
formation_model_file = "./Input/Formation.txt" # path to file with formation parameters
borehole_model_file = "./Input/Borehole.txt" # path to file with borehole parameters
measurement_depths = np.arange(0, 25.1, 0.25) # measurement points

In [4]:
# Set tools parameters
tools_parameters = rm.SetToolsParameters(tools)

for tool in list(tools_parameters.keys()):
    print(tool)
    print(tools_parameters[tool][0])
    print(tools_parameters[tool][1])
    print()

B5.7A0.4M
[[-5.9        -0.2         0.2         5.37928847]
 [-1.          1.          0.         -3.05      ]]
[[-5.9        -0.2         0.2         5.37928847]
 [ 0.          0.          1.          0.2       ]]

M5.7N0.4A
[[-5.9        -0.2         0.2         5.37928847]
 [ 0.          0.          1.          0.2       ]]
[[-5.9        -0.2         0.2         5.37928847]
 [ 0.          0.          1.          0.2       ]]

M2.0A0.5B
[[ -2.25        -0.25         0.25       125.66370614]
 [  0.           1.          -1.           0.        ]]
[[ -2.25        -0.25         0.25       125.66370614]
 [  1.           0.           0.          -2.25      ]]

A2.0M0.5N
[[ -2.25        -0.25         0.25       125.66370614]
 [  1.           0.           0.          -2.25      ]]
[[ -2.25        -0.25         0.25       125.66370614]
 [  1.           0.           0.          -2.25      ]]



In [12]:
def prepare_modeling_tasks(tools_parameters, measurement_depths):

    current_electrode_depths = {}
    for tool in tools_parameters.keys():
        current_electrode_depths[tool] = measurement_depths + tools_parameters[tool][1][1,3] 
    simulation_depths = np.unique(np.hstack(list(current_electrode_depths.values())))
    
    tasks = []
    for simulation_depth_index in range(len(simulation_depths)):
        
        simulation_depth = simulation_depths[simulation_depth_index]
        modelling_tasks = []
        potential_electodes_depths = []
        for tool_index in range(len(list(tools_parameters.keys()))):
            tool = list(tools_parameters.keys())[tool_index]
            if np.any(np.isclose(current_electrode_depths[tool], simulation_depth)):
                measurement_depth_index = np.argwhere(np.isclose(measurement_depths + tools_parameters[tool][1][1,3], simulation_depth))[0][0]
                modelling_tasks.append([tool_index, measurement_depth_index])
                tool_electrodes = tools_parameters[tool][1][:,:3].copy() 
                tool_electrodes[0,:] -= tools_parameters[tool][1][1,3] 
                potential_electodes_depths += list(tool_electrodes[0, tool_electrodes[1,:]==0])
                

        unique_potential_electodes_depths = np.unique(potential_electodes_depths)
        combined_tools = np.zeros((2, len(unique_potential_electodes_depths)+1))
        combined_tools[1,0] = 1
        combined_tools[0,1:] = unique_potential_electodes_depths
        combined_tools = combined_tools[:,combined_tools[0,:].argsort()]
        print(combined_tools)
        tasks.append([[simulation_depth_index, combined_tools], modelling_tasks])
        #print([simulation_depth_index, combined_tools, modelling_tasks])
    
    return simulation_depths, tasks

tasks = prepare_modeling_tasks(tools_parameters, measurement_depths)

[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.4  0. ]
 [ 0.   0.   1. ]]
[[0.  2.  2.5]
 [1.  0.  0. ]]
[[-6.1 -0.

In [ ]:
# Set model parameters
model_parameters = rm.SetModelParameters(formation_model_file, borehole_model_file)
# model_parameters

In [ ]:
# rm.ComputeSyntheticLogs_v2(tools_parameters, model_parameters, measurement_depths, tools_version="alternative",
#                                domain_radius=25, processes=12, mesh_generator="netgen")